# Generated by Django 2.2 on 2020-02-17 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tv_shows_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='show',
            name='description',
            field=models.TextField(default='whoops'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='show',
            name='release_date',
            field=models.TextField(default='whoop again'),
            preserve_default=False,
        ),
    ]
