# Generated by Django 2.2 on 2020-02-14 16:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mtm_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='owner',
            name='age',
            field=models.IntegerField(),
        ),
        migrations.CreateModel(
            name='Chipmunk',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('description', models.TextField()),
                ('phone_number', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chipmunks', to='mtm_app.Owner')),
                ('owners_that_voted', models.ManyToManyField(related_name='chipmunks_voted_for', to='mtm_app.Owner')),
            ],
        ),
    ]
